<?php

namespace AppBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{

    public function getNews()
    {
        $qb = $this->createQueryBuilder('n');

        $qb->orderBy('n.createdAt', 'DESC');

        return $qb->getQuery()->getResult();
    }

}
