<?php

namespace AppBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{

    public function getNews()
    {
        $qb = $this->createQueryBuilder('n');

        $qb->andWhere('n.publishAt <= :now')
            ->setParameter('now', new \DateTime());

        $qb->orderBy('n.publishAt', 'DESC');

        return $qb->getQuery();
    }

}
