# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.admin.node:
        class: AppBundle\Admin\NodeAdmin
        arguments: [~, AppBundle\Entity\Node, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Node }
