services:
    app.admin.team:
        class: AppBundle\Admin\TeamAdmin
        arguments: [~, AppBundle\Entity\Team, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Team }
